language: python
branches:
  only:
  - src
install:
- pip install -r requirements.txt
script:
- make github
env:
  global:
    secure: S6NtbHjOB+Ut68Y1OYfDrMz0e3EkwovrGGwTE+Wz64x0UcPY1cDdbRdXaU3yNWBS3IQJbinGX+LRojsduRi2emVXE5RXwvlulSN9CDDHJTAvN2KXGh59IB3agBa/bhEGN83sTNn9lNarWfciyE9kEPzAwPztCKCHxvp7uTmCe7uTXlvuPkh4TDpEQw0WEBYS3Vf85H1NJYSV3AYMbMEe/FMdNID/7zhnNmjSxlDwSM0VAw83xYsbpjLah0SYnaVy1qhLxG0qAr+3Rjg9bmNj+vMYYRo1H4DlwhqpWqcIu+2qnFqxfrnPqNBrd56rLtgBZI37xK7FjWcXaOB4xWUwrIxqcrjzA0dgVnudG4fT1WzD7imy+EJdnx/tAg6M8PBx6wXp262n2hA91kOQg34F3rgfYaqWlB9ShlDyDLhgr50blhRUJ0l4+Hz9TUCL1T0/piYiuFr43G1VC1s5j2aG2Crpw5IeYRdb+GY7mOAXKBRhb1K53CTRIzbxzNYvbpe3fHadWK4y0a49vXrp3Z9npv4yKScGjxggvL2x1Ps0W3ujxgve5Cg294yqIh8iip/slu5De5+pyoqO+5+t4bE9StYP3gScZTj6uG75CphwPt9FpYBGx/8OG9XIS1TiKg2Nl/qJGlTdG5qmUMw96SL0iExHCNlKl7Ue70eaWmlJeQ4=
